apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: web-critical
  name: first-pod
spec:
  containers:
  - image: nginx:1.19.2
    name: web
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
