apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  volumes:
  - name: sharedvol
    emptyDir: {} 
  initContainers:
  - name: delay
    image: busybox
    command: ['sh','-c','sleep 15']
  - name: prepare
    image: alpine:3.22.2 
    command: ['sh', '-c', 'apk update; apk add git; git clone -b develop https://github.com/mariano-italiano/kubernetes-sm1.git /app']
    volumeMounts:
    - name: sharedvol 
      mountPath: /app
  containers:
  - name: web
    image: nginx
    volumeMounts:
    - name: sharedvol
      mountPath: /usr/share/nginx/html

