apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: web
      image: nginx
      volumeMounts:
      - name: config-volume
        mountPath: /etc/nginx
      - name: htpasswd-volume
        mountPath: /etc/nginx/conf
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config 
    - name: htpasswd-volume
      secret:
        secretName: nginx-htpasswd

